PEOPLE: list[dict] = [
    {
        "slug": "andrej-karpathy",
        "name": "Andrej Karpathy",
        "title": "Researcher",
        "org": "Eureka Labs",
        "aliases": ["Karpathy", "Andrej"],
    },
    {
        "slug": "dario-amodei",
        "name": "Dario Amodei",
        "title": "CEO",
        "org": "Anthropic",
        "aliases": ["Dario"],
    },
    {
        "slug": "sam-altman",
        "name": "Sam Altman",
        "title": "CEO",
        "org": "OpenAI",
        "aliases": ["Altman", "Sam"],
    },
    {
        "slug": "demis-hassabis",
        "name": "Demis Hassabis",
        "title": "CEO",
        "org": "Google DeepMind",
        "aliases": ["Hassabis", "Demis"],
    },
    {
        "slug": "yann-lecun",
        "name": "Yann LeCun",
        "title": "Chief AI Scientist",
        "org": "Meta",
        "aliases": ["LeCun", "Yann"],
    },
    {
        "slug": "satya-nadella",
        "name": "Satya Nadella",
        "title": "CEO",
        "org": "Microsoft",
        "aliases": ["Nadella", "Satya"],
    },
    {
        "slug": "greg-brockman",
        "name": "Greg Brockman",
        "title": "President",
        "org": "OpenAI",
        "aliases": ["Brockman", "Greg"],
    },
    {
        "slug": "patrick-collison",
        "name": "Patrick Collison",
        "title": "CEO",
        "org": "Stripe",
        "aliases": ["Collison", "Patrick"],
    },
    {
        "slug": "ilya-sutskever",
        "name": "Ilya Sutskever",
        "title": "Co-founder",
        "org": "SSI",
        "aliases": ["Sutskever", "Ilya"],
    },
    {
        "slug": "jensen-huang",
        "name": "Jensen Huang",
        "title": "CEO",
        "org": "NVIDIA",
        "aliases": ["Jensen", "Huang", "Jen-Hsun"],
    },
]
