TOPICS: list[dict] = [
    {"slug": "ai-agents", "name": "AI agents"},
    {"slug": "scaling", "name": "Scaling"},
    {"slug": "alignment", "name": "Alignment"},
    {"slug": "open-source-ai", "name": "Open-source AI"},
    {"slug": "software-development", "name": "Software development"},
    {"slug": "coding-agents", "name": "Coding agents"},
    {"slug": "regulation", "name": "Regulation"},
    {"slug": "compute", "name": "Compute"},
    {"slug": "inference", "name": "Inference"},
    {"slug": "foundation-models", "name": "Foundation models"},
    {"slug": "startups", "name": "Startups"},
    {"slug": "hiring", "name": "Hiring"},
    {"slug": "research", "name": "Research"},
    {"slug": "robotics", "name": "Robotics"},
    {"slug": "chips", "name": "Chips"},
    {"slug": "energy", "name": "Energy"},
    {"slug": "safety", "name": "Safety"},
    {"slug": "evals", "name": "Evals"},
    {"slug": "product", "name": "Product"},
    {"slug": "capital", "name": "Capital"},
    {"slug": "open-weights", "name": "Open weights"},
    {"slug": "data", "name": "Data"},
    {"slug": "multimodality", "name": "Multimodality"},
    {"slug": "agi", "name": "AGI"},
    {"slug": "labor", "name": "Labor"},
    {"slug": "books", "name": "Books"},
    {"slug": "apps", "name": "Apps"},
    {"slug": "tools", "name": "Tools"},
    {"slug": "personal-stack", "name": "Personal stack"},
]
